### ISSUE TITLE
Address warnings when importing Ecoscope in Colab

### ISSUE THREAD

**Issue by walljcg** [wildlife-dynamics/ecoscope#149]
Circa May 8 we started receiving the following warnings when importing Ecoscope within Colab.

/usr/local/lib/python3.10/dist-packages/cudf/utils/_ptxcompiler.py:61: UserWarning: Error getting driver and runtime versions:

stdout:

stderr:

Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/usr/local/lib/python3.10/dist-packages/numba/cuda/cudadrv/driver.py", line 295, in __getattr__
    raise CudaSupportError("Error at driver init: \n%s:" %
numba.cuda.cudadrv.error.CudaSupportError: Error at driver init: 

CUDA driver library cannot be found.
If you are sure that a CUDA driver is installed,
try setting environment variable NUMBA_CUDA_DRIVER
with the file path of the CUDA driver shared library.
:

Not patching Numba
  warnings.warn(msg, UserWarning)
/usr/local/lib/python3.10/dist-packages/cudf/utils/gpu_utils.py:62: UserWarning: Failed to dlopen libcuda.so.1
  warnings.warn(str(e))
/usr/local/lib/python3.10/dist-packages/cudf/utils/gpu_utils.py:62: UserWarning: Function "cuInit" not found
  warnings.warn(str(e))

**Comment by atmorling** [comment]
When `cudf`  is imported without a CUDA driver (as it is in non-GPU enabled Colab environments), the above warning occurs.

`datashader` has an optional dependency on `cudf`, and will import it if found.
Since `cudf-cu12` is installed by default in Colab, we get this warning in Colab when importing `datashader`.

This can be verified by starting a fesh Colab notebook, pip installing `datashader` and then attempting to import.
I can also replicate this warning on my local machine (which is NVIDIA free) by pip installing `cudf-cu12` and then importing `datashader`

**Comment by atmorling** [comment]
Closed with #178
