### ISSUE TITLE
warning while creating temporal index grouper

### ISSUE THREAD

**Issue by walljcg** [wildlife-dynamics/ecoscope#160]
We're getting a warning when running this line of code: 

ecoscope.base.utils.add_temporal_index(events, 'year', 'time', '%Y')

/usr/local/lib/python3.10/dist-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

see for example: https://colab.research.google.com/drive/1kI7PMJI-LLiHukcsKgrUUhxPGnKZnBBJ?authuser=1#scrollTo=MlheeTNubqst

**Comment by Yun-Wu** [comment]
The warning is caused by the non-deterministic behavior of value assignment in pandas DataFrames. In this example, after the clip operation, the resulting events DataFrame may either be a view or a copy of the original tb_obs DataFrame. Consequently, changes to events might or might not affect tb_obs, which causes the warning. Using .loc on events does not resolve this issue. 

Luckily, pandas introduced [`copy-on-write`](https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#) from 1.5.0, which ensures that any write operation always creates a copy of the DataFrame, leading to more predictable behavior. This feature will become the default in pandas 3.0. Given that we are using pandas 2.2.2, I have enabled it in the ecoscope.init() function to ensure consistent behavior.

Tested in the notebook and the warning is gone.
