### ISSUE TITLE
Day Night

### ISSUE THREAD

**Issue by Ankabedettidk** [wildlife-dynamics/ecoscope#2]
More of a question than an issue.
How is day and night defined ? Is there a piece of code that allows to define the day/night cut off hours manually ?

**Comment by cath34** [comment]
Hi,
The day/night calculation is based on the horizon of each location. If the sun is below the horizon, it will return True. Otherwise, it will return False. We could easily modify this function to allow users to specify degrees above/below the horizon to calculate day/night (For example, setting the threshold at 6 degrees below horizon instead of 0). Let us know if this feature would be useful for you.

**Comment by Ankabedettidk** [comment]
Wow that is great ! For now, this feature will do as is. Thank you :)
