### ISSUE TITLE
Align .github/workflows to ecoscope-workflows

### ISSUE THREAD

**Issue by atmorling** [wildlife-dynamics/ecoscope#247]
Now that we have optional dependency lists here, we can update the workflows in this repo to do something like `pip install ecoscope[test]`, rather than need an `environment.yml`/mamba setup step. Would bring this repo into alignment with other ecoscope repos.

**Comment by cisaacstern** [comment]
> we can update the workflows in this repo to do something like pip install ecoscope[test], rather than need an environment.yml/mamba setup step

Very glad to see this mentioned. While of course inter-repo stylistic/tooling alignment is helpful for DX, I would actually suggest you've sort of buried the lede on the title of this issue.

IMHO, this will be a dramatic improvement because we will actually be testing against the same environment users will get when they install from pip. I realize that the sort of de-facto install pathway up until now has been conda, and that geopandas itself does recommend conda, but that being said, in `ecoscope-workflows` (up until now, at least), we are only using pip (including for geopandas), and all seems fine so far.

If for some reason we determine a conda env is truly necessary because pip cannot correctly resolve geopandas (or related binaries), then we should make that much more clearly the recommended installation method (as geopandas itself does). I am hopeful, though, that perhaps pip is sufficient for many/most use cases, as it's just lighter weight. 🤞

**Comment by cisaacstern** [comment]
> I am hopeful, though, that perhaps pip is sufficient for many/most use cases, as it's just lighter weight. 🤞

A mere few hours later and I think I am finally understanding (through painful experience of broken environments in workflows) that tempting the fates by not using conda to install geopandas is perhaps, I quite bad idea. 😅

**Comment by atmorling** [comment]
So based on that and what we discussed at standup today, the task here would be to A) add caching for deps and B) Make the install of 'ecoscope' under test more transparent
